CREATE TABLE Productreceipts(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID not null,
    user_id INT NOT NULL,
    contractor_id INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    document_number VARCHAR(50) NOT NULL,
    CONSTRAINT fk_productreceipt_user
        FOREIGN KEY (user_id)
            REFERENCES users(id),
    CONSTRAINT fk_productreceipt_contractor
        FOREIGN KEY (contractor_id)
            REFERENCES contractors(id)
);
CREATE TABLE Productissues(
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        uuid UUID not null,
        user_id INT NOT NULL,
        contractor_id INT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        document_number VARCHAR(50) NOT NULL,
        CONSTRAINT fk_productissue_user
            FOREIGN KEY (user_id)
                REFERENCES users(id),
        CONSTRAINT fk_productissue_contractor
            FOREIGN KEY (contractor_id)
                REFERENCES contractors(id)
)