CREATE TABLE warehouses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID not null UNIQUE,
    name VARCHAR(30) NOT NULL
);

CREATE TABLE halls (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID not null UNIQUE,
    name VARCHAR(30) NOT NULL,
    id_warehouse INT NOT NULL,
    CONSTRAINT fk_hall_warehouse
        FOREIGN KEY (id_warehouse)
            REFERENCES warehouses (id)
            ON DELETE CASCADE
);

CREATE TABLE shelves (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID not null UNIQUE,
    name VARCHAR(30) NOT NULL,
    id_hall INT NOT NULL,
    CONSTRAINT fk_shelf_hall
        FOREIGN KEY (id_hall)
            REFERENCES halls (id)
            ON DELETE CASCADE
);

CREATE TABLE spots (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID not null UNIQUE,
    name VARCHAR(30) NOT NULL,
    id_shelf INT NOT NULL,
    is_free BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT fk_spot_shelf
        FOREIGN KEY (id_shelf)
            REFERENCES shelves (id)
            ON DELETE CASCADE
);
