CREATE TABLE warehouses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID not null UNIQUE,
    name VARCHAR(30) NOT NULL
);

CREATE TABLE halls (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID not null UNIQUE,
    name VARCHAR(30) NOT NULL,
    id_warehouse INT NOT NULL,
    CONSTRAINT fk_hall_warehouse
        FOREIGN KEY (id_warehouse)
            REFERENCES warehouses (id)
            ON DELETE CASCADE
);

CREATE TABLE shelves (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID not null UNIQUE,
    name VARCHAR(30) NOT NULL,
    id_hall INT NOT NULL,
    CONSTRAINT fk_shelf_hall
        FOREIGN KEY (id_hall)
            REFERENCES halls (id)
            ON DELETE CASCADE
);

CREATE TABLE spots (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID not null UNIQUE,
    name VARCHAR(30) NOT NULL,
    id_shelf INT NOT NULL,
    CONSTRAINT fk_spot_shelf
        FOREIGN KEY (id_shelf)
            REFERENCES shelves (id)
            ON DELETE CASCADE
);

CREATE TABLE locations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID not null UNIQUE,
    id_warehouse INT NOT NULL,
    id_hall INT NOT NULL,
    id_shelf INT NOT NULL,
    id_spot INT NOT NULL,
    isfree BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_location_warehouse
        FOREIGN KEY (id_warehouse)
            REFERENCES warehouses (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_location_hall
        FOREIGN KEY (id_hall)
            REFERENCES halls (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_location_shelf
        FOREIGN KEY (id_shelf)
            REFERENCES shelfs (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_location_spot
        FOREIGN KEY (id_spot)
            REFERENCES spots (id)
            ON DELETE CASCADE
);
