CREATE TABLE productdetails (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        description VARCHAR(200) not null,
        weight real,
        width real,
        height real,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE categories (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(45)
);
CREATE TABLE products (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID not null UNIQUE,
    rfid VARCHAR(30) not null UNIQUE,
    name varchar(30) not null,
    product_receipt_id int,
    product_issue_id int,
    category_id int not null,
    product_details_id int not null,
    location_id int not null,
    contractor_id int not null,
    user_id int not null,
    is_active boolean DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_product_productdetails
        FOREIGN KEY (product_details_id)
            REFERENCES productdetails (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id)
            REFERENCES categories (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_product_location
        FOREIGN KEY (location_id)
            REFERENCES Locations (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_product_user
        FOREIGN KEY (user_id)
            REFERENCES Users (id)
            ON DELETE CASCADE

);