CREATE TABLE inventories(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL,
    date TIMESTAMPTZ NOT NULL DEFAULT now(),
    supervisor_id INT NOT NULL,
    hall_id INT NOT NULL,
    note VARCHAR(200),
    CONSTRAINT fk_inventory_user
        FOREIGN KEY (supervisor_id)
            REFERENCES users(id),
    CONSTRAINT fk_inventory_hall
        FOREIGN KEY (hall_id)
            REFERENCES halls(id)
)