CREATE TABLE transfers(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id int NOT NULL,
    spot_from_id int NOT NULL,
    spot_to_id int NOT NULL,
    supervisor_id int NOT NULL,
    date TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_transfer_product
        FOREIGN KEY (product_id)
            REFERENCES products(id),
    CONSTRAINT fk_transfer_user
        FOREIGN KEY (supervisor_id)
            REFERENCES users(id),
    CONSTRAINT fk_transfer_spot_from
        FOREIGN KEY (spot_from_id)
            REFERENCES spots(id),
    CONSTRAINT fk_transfer_spot_to
        FOREIGN KEY (spot_to_id)
            REFERENCES spots(id)
)