CREATE TABLE Producthistory(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id int NOT NULL,
    user_id int NOT NULL,
    action_type VARCHAR(15) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_producthistory_product
        FOREIGN KEY (product_id)
            REFERENCES products(id)
                ON DELETE CASCADE,
    CONSTRAINT fk_producthistory_user
        FOREIGN KEY (user_id)
            REFERENCES users(id)
                ON DELETE CASCADE
)