CREATE TABLE "users"
(
    id        serial primary key,
    uuid      varchar not null,
    name      varchar not null,
    surname   varchar not null,
    username     varchar not null,
    password     varchar not null,
    email  varchar not null,
    role      varchar not null,
    isEnable    boolean DEFAULT true,
    isLock boolean DEFAULT false
);
INSERT INTO users (uuid, name, surname, username, password, email, role, isEnable, isLock)
VALUES (
           'adba5ccc-f717-4dd9-bad2-d43ac72adc4b',
           'Jan',
           'Kowalski',
           'jan$kowalski1234',
           '$2a$10$JwOJl2S5y9TDLzsVoPvnkO2BemIxFbZpXdBfhU.W3bzNp.jYxp/Bm',
           'jan.kowalski@example.com',
           'ADMIN',
           true,
           false
       );
CREATE TABLE reports(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    type VARCHAR NOT NULL,
    content VARCHAR(200) NOT NULL,
    done boolean DEFAULT false,
    CONSTRAINT fk_report_user
        FOREIGN KEY(user_id)
            REFERENCES users(id)
)