CREATE TABLE contractors(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    name Varchar(45) NOT NULL,
    phone VARCHAR(9) NOT NULL,
    email VARCHAR(45) NOT NULL,
    account_manager_id INT NOT NULL,
    CONSTRAINT fk_contractor_supervisor
        FOREIGN KEY (account_manager_id)
            REFERENCES users (id)
            ON DELETE CASCADE
)